bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 20
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 1.0
logging_dir = "D:/SD/ResultingModels/FinalModel/nikolailic_finalModel\\log"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 1360
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 13600
min_bucket_reso = 256
mixed_precision = "bf16"
multires_noise_discount = 0.3
network_alpha = 64
network_args = []
network_dim = 128
network_module = "networks.lora"
noise_offset_type = "Original"
optimizer_args = [ "decouple=True", "weight_decay=0.2", "betas=0.9,0.99",]
optimizer_type = "DAdaptation"
output_dir = "D:/SD/ResultingModels/FinalModel/nikolailic_finalModel\\model"
output_name = "nikolailic_finalModel_realVis"
pretrained_model_name_or_path = "D:/SD/stable-diffusion-webui-1.9.4/models/Stable-diffusion/Realistic_Vision_V5.1.safetensors"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = "D:/SD/ResultingModels/FinalModel/nikolailic_finalModel\\model\\prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
text_encoder_lr = 1
train_batch_size = 1
train_data_dir = "D:/SD/ResultingModels/FinalModel/nikolailic_finalModel\\img"
unet_lr = 1
xformers = true
